### PR TITLE
Lock openapi schema version for swagger UI to 3.0.2

### PR DESCRIPTION
**Pull request by dancoates**
Not quite sure why this suddenly broke, but this seems to fix it

### CODE REVIEW

**Review by illusional — COMMENTED** [review]
I thought swagger UI would support 3.1.0 fine? Or if it's the react flavour, should update swagger on the front-end.

The actual openapi generator should not use this function anymore.

**Comment by dancoates** [comment]
Yeah fair point, I was tossing up whether to upgrade the swagger UI, it's a major version upgrade so could break things but I'll give it a shot

**Comment by dancoates** [comment]
@illusional I had a crack at updating to the new swagger ui react to support openapi def 3.1.0, but it is a bit of a rabbit hole, v5 of swagger UI requires v9 of react-redux which requires v18 of react, and upgrading to v18 of react requires updating most of our component libraries, I'm not even sure all of them will support react 18. I think it'd be good to get temporary fix out and look at upgrading react separately.

**Review by illusional — APPROVED** [review]
Ooft, what a rabbit hole.

**Pull request merged**
